### PR TITLE
Add Careers page

### PR DESCRIPTION
**Pull request by raney24**

### CODE REVIEW

**Comment by raney24** [comment]
@WillGarman What do you think about just using the `type: 'block'` for the career body instead of having to use all of the fields, let them post it however they would like? (see commit above)

**Comment by raney24** [comment]
@WillGarman Oops, forgot to track it. Should be added now

**Comment by WillGarman** [comment]
@raney24 I added an active slider and changed the preview to show the job title and active or not. 

Is there anything else you think needs added. I think this is a solid starting point for the page to be made

**Comment by raney24** [comment]
@WillGarman That looks good to me. Good starting point to connect it on the frontend.

**Comment by Sisay-su** [comment]
@raney24 This is ready for review.

**Comment by WillGarman** [comment]
@Sisay-su this looks great, awesome job on this!

**Pull request merged**
